version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      target: development
    container_name: frontend_dev
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - ../frontend/.env
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ../backend
    container_name: backend_dev
    volumes:
      - ../backend:/app
    ports:
      - "5001:5000"
    env_file:
      - ../backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

